import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

export const pexelsApi = createApi({
  reducerPath: "pexelsApi",
  baseQuery: fetchBaseQuery({
    baseUrl: "https://api.pexels.com/v1/",
    // Pexels expects the API key in the Authorization header, without a prefix
    prepareHeaders: (headers) => {
      headers.set("Authorization", import.meta.env.VITE_PEXELS_KEY);
      return headers;
    },
  }),
  endpoints: (builder) => ({
    getPhotoById: builder.query({
      query: (id) => `photos/${id}`,
    }),
  }),
});

// Generated by RTK Query from the endpoint name
export const { useGetPhotoByIdQuery } = pexelsApi;
